export const userContants = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE'
}

export const statesContants = {
  GET_STATES_SUCCESS: 'GET_STATES_SUCCESS',
  GET_STATES_FAILURE: 'GET_STATES_FAILURE'
}

export const flightsContants = {
  GET_ARRIVING_FLIGHT_SUCCESS: 'GET_ARRIVING_FLIGHT_SUCCESS',
  GET_DEPARTING_FLIGHT_SUCCESS: 'GET_DEPARTING_FLIGHT_SUCCESS',
  GET_FLIGHTS_SUCCESS: 'GET_FLIGHTS_SUCCESS',
  GET_FLIGHT_FAILURE: 'GET_FLIGHT_FAILURE',
}

export const IS_REQUESTING = 'IS_REQUESTING';